bind = Super, Print, exec, sh -c "~/scripts/print_activewindow.sh" # 截取当前活动的窗口
bind = , Print, exec, grim - | wl-copy # 截取整个屏幕
bind = Super, C, exec, $editor # 启动代码编辑器
bind = , XF86TouchpadToggle, exec, sh -c "~/scripts/touchpad_toggle.sh" # 切换触控板状态
